config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles

  validates :username,  presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,     presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX, message: "allow only valid email address" }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def show

  end
  def index
    @articles = Article.all
  end

  def new
    @obj = Article.new
  end

  def edit

  end

  def create
    @obj = Article.new(article_params)
    @obj.user = User.first
    if @obj.save
      flash[:notice] = "Article was created successfully."
      redirect_to @obj
    else
      render 'new'
    end
  end

  def update
    if @obj.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @obj
    else
      render 'edit'
    end
  end

  def destroy
    @obj.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:obj).permit(:title, :description)
  end

  def set_article
    @obj = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end

    @user.username = params[:username]
    @user.email = params[:email]
    @user.password = params[:password]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Alpha Blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="col-10">
        <%= render '/shared/errors', obj: @article %>
        <%= form_with(model: @obj, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="cal-10">
              <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label text-light" %>
            <div class="cal-10">
              <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
            </div>
          </div>


          <%= f.submit class: "btn btn-outline-success btn-lg mt-4" %>
        <% end %>
        <div class="mb-3">
          <%= link_to '[ Cancel and return to article listing ]', articles_path, class: "text-info" %>
        </div>
      </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= article.user.username %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created ago <%= time_ago_in_words(article.created_at) %>,
              edited ago <%= time_ago_in_words(article.updated_at) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Crete a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @obj.title %></h2>

<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @obj.user.username %>
          </div>
          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@obj.description) %></div>
            <%= link_to "Edit", edit_article_path(@obj), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@obj), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created ago <%= time_ago_in_words(@obj.created_at) %>,
              edited ago <%= time_ago_in_words(@obj.updated_at) %></small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt_auto py-3 bg-dark" id="sticky-footer">
  <div class="container text-center text-white">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"/>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Create new articles", new_article_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<H1>This is about</H1>

<%=link_to 'Article listing listing', articles_path %> |
<%=link_to 'Home page', root_path %> |

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="bg-light p-5 rounded-lg m-3 text-center rounded text-white" id="jumbotron">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-success" %>
  </div>
</div>

<!--<%#=link_to 'Article listing listing', articles_path %> |-->
<%#=link_to 'About page', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"/>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render '/shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="cal-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="cal-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="cal-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose password" %>
          </div>
        </div>


        <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-outline-success btn-lg mt-4") %>
      <% end %>
      <div class="mb-3">
        <%= link_to '[ Cancel and return to article listing ]', articles_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>